# The IP addresses(s) the SSH server will listen on. Use a comma separated list for multiple addresses.
# Leave as "0.0.0.0" for all addresses.
listenAddress: 0.0.0.0
# The port the SSH server will listen on.
port: 22

# By default, only public key authentication is enabled. This is the most secure mode.
# To authorize a user to log in with public key authentication, install their public
# PEM certificate in the authorized_users directory. Name the key file with user's user
# name (no file extension).
