name: BukkitSSH
version: ${project.version}
api-version: 1.13
authors: [Ryan Michela, Haarolean, toxuin, _Fleek]
main: me.focusvity.bukkitssh.BukkitSSH
description: A plugin that gives people access to SSH console